name: Publish to CodeArtifact

on:
  release:
    types: [published]

env:
  AWS_REGION: us-east-1

jobs:
  publish:
    runs-on:
      group: Infrastructure
      labels: [self-hosted, linux, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Login to CodeArtifact
      run: |
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain ${{ vars.CODEARTIFACT_DOMAIN }} \
          --domain-owner ${{ vars.CODEARTIFACT_DOMAIN_OWNER }} \
          --region ${{ env.AWS_REGION }} \
          --query authorizationToken \
          --output text)
        cat <<EOS > gradle.properties
          mavenUrl=${{ vars.CODEARTIFACT_DOMAIN }}-${{ vars.CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.${{ env.AWS_REGION }}.amazonaws.com/maven/java
          mavenUser=aws
          mavenPassword=$CODEARTIFACT_AUTH_TOKEN
        EOS

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Publish to CodeArtifact
      run: ./gradlew publish

